// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPDntI4_deqWn1BXCbI3wF9bN99VpvTQ',
    appId: '1:976670828273:web:fc53c77b64d03363d4ab50',
    messagingSenderId: '976670828273',
    projectId: 'taskapp-a2540',
    authDomain: 'taskapp-a2540.firebaseapp.com',
    storageBucket: 'taskapp-a2540.appspot.com',
    measurementId: 'G-NDCC7S2MPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4-WCTXj-H8cn4bahfNhpw-8xIdUePl8',
    appId: '1:976670828273:android:db1b7c73d3856f79d4ab50',
    messagingSenderId: '976670828273',
    projectId: 'taskapp-a2540',
    storageBucket: 'taskapp-a2540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVbSacZR5jgGxkWXAUc6Cg7QhK1PrQho',
    appId: '1:976670828273:ios:e868080aedc86c15d4ab50',
    messagingSenderId: '976670828273',
    projectId: 'taskapp-a2540',
    storageBucket: 'taskapp-a2540.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVbSacZR5jgGxkWXAUc6Cg7QhK1PrQho',
    appId: '1:976670828273:ios:e868080aedc86c15d4ab50',
    messagingSenderId: '976670828273',
    projectId: 'taskapp-a2540',
    storageBucket: 'taskapp-a2540.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPDntI4_deqWn1BXCbI3wF9bN99VpvTQ',
    appId: '1:976670828273:web:99c6a1e495f765a9d4ab50',
    messagingSenderId: '976670828273',
    projectId: 'taskapp-a2540',
    authDomain: 'taskapp-a2540.firebaseapp.com',
    storageBucket: 'taskapp-a2540.appspot.com',
    measurementId: 'G-WR4Z3L7C10',
  );
}
